// SPDX-License-Identifier: MIT
//
// Core domain types. Streaming-first: consumers receive a union of
// FindEvent values from the async generator, never a final snapshot.

import type { Confidence, CostUnit } from "@icpfinder/providers";

/**
 * A target persona. Generated by the LLM from the seed input.
 * Stable shape — UI cards depend on these fields.
 */
export interface ExampleCompany {
  /** Display name as the LLM returned it. */
  name: string;
  /** Lowercase bare domain, no protocol, no www, no path. */
  domain: string;
  /** One-line "why this company NOW" — concrete trigger the LLM inferred
   * (recent funding, hiring spike, expansion, etc.). May be empty. */
  whyNow?: string;
}

export interface Archetype {
  /** Stable ID derived from index — `arch_0`, `arch_1`. */
  id: string;
  industry: string;
  role: string;
  companySize: string;
  pain: string;
  /** Why this archetype belongs in the set — short paragraph explaining
   * the LLM's selection criteria for this persona. Collapsible in UI. */
  reasoning?: string;
  /** One-line outreach hook tailored to the persona. Rendered as the
   * mint-tinted "pitch angle" callout. */
  sellingAngle?: string;
  buyingSignals: string[];
  /** Top likely "no" objections this persona would raise — 3 short lines. */
  objections?: string[];
  /** Real companies matching this archetype, returned by the LLM.
   * May be empty if the model declined to name any. */
  exampleCompanies: ExampleCompany[];
}

/**
 * One enriched company + contact pair tied to a parent archetype.
 * Email is nullable — verification can fail.
 */
export interface Candidate {
  id: string;
  archetypeId: string;
  companyName: string;
  domain: string;
  contactFirstName: string | null;
  contactLastName: string | null;
  contactRole: string | null;
  contactEmail: string | null;
  emailConfidence: Confidence | null;
  emailScore: number | null;
  /** Populated by /api/deepen — empty by default. */
  whyNow?: string;
}

/**
 * Deepen response — Gemini-grounded trigger + provenance + dossier.
 * Returned by /api/deepen, never streamed by core IcpFinder.find().
 */
export interface DeepenResult {
  candidateId: string;
  trigger: string;
  /** Sanitized http(s) URL — only http/https accepted by renderer. */
  provenanceUrl: string | null;
  dossier: string;
}

/**
 * Discriminated union streamed by `IcpFinder.find()`. Order is not
 * guaranteed except that `archetype` events arrive before any
 * `candidate` referencing that archetype.
 */
export type FindErrorCode = "auth" | "rate_limit" | "quota" | "network" | "unknown";
export type FindErrorProvider = "gemini" | "hunter";

export type FindEvent =
  | { type: "archetype"; archetype: Archetype }
  | { type: "candidate"; candidate: Candidate }
  | { type: "cost"; cost: CostUnit }
  | {
      type: "error";
      message: string;
      recoverable: boolean;
      code?: FindErrorCode;
      provider?: FindErrorProvider;
    }
  | { type: "done"; totalCostCents: number };

export interface FindInput {
  /**
   * Free-form description of the product or company. The LLM derives
   * archetypes from this. Required.
   */
  seed: string;
  /** Max archetypes to generate. Default 3. */
  archetypeLimit?: number;
  /** Max candidates per archetype. Default 5. */
  candidatesPerArchetype?: number;
  /** Hard cap on total spend in cents. Generator stops when reached. */
  budgetCapCents?: number;
  /** Enable Google-grounded search for archetype generation. */
  grounding?: boolean;
  /** Abort signal — consumer cancels the run. */
  signal?: AbortSignal;
}
